# Generated by Django 4.1.6 on 2023-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('comapny_name', models.CharField(max_length=500)),
                ('company_location', models.CharField(max_length=300)),
                ('company_about', models.CharField(max_length=300)),
                ('company_type', models.CharField(choices=[('IT', 'IT'), ('Service', 'Service')], max_length=400)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
