# Generated by Django 4.1.6 on 2023-03-07 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=100)),
                ('dep_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_sal', models.IntegerField(default=0)),
                ('emp_phone', models.IntegerField(default=0)),
                ('emp_hire_date', models.DateField()),
                ('emp_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAPI.department')),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpAPI.roles')),
            ],
        ),
    ]
