# Generated by Django 4.1.6 on 2023-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
